trigger:
- main

pool:
 name: Local

variables:
  buildConfiguration: 'Release'

resources:
  repositories:
    - repository: geekymon2
      type: git
      name: tasker
      ref: $(Build.SourceBranch)  

steps:
# Checkout
- checkout: self
  clean: true
  persistCredentials: true
  fetchDepth: 1

# Install
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 8.x

# Restore
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    arguments: --force
    feedsToUse: 'select'
    vstsFeed: 'geekymon2'

# Build
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet publish $(buildConfiguration)'

# Publish the zip file as a universal package to Azure Artifacts
- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.SourcesDirectory)/bin/$(buildConfiguration)/net8.0/'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: 'Tasker/tasker'
    vstsFeedPackagePublish: 'tasker'
    versionOption: 'custom'
    versionPublish: '1.0.$(Build.BuildId)'
  
    packagePublishDescription: 'Build output as a zip file'

- script: |
    git config --global user.name "Build Host"
    git config --global user.email "buildagent@$(Environment.Name)"
    git tag -a v1.0.$(Build.BuildId) -m "Release v1.0.$(Build.BuildId)"
    git push
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Tag source code with the build number and push'